
services:
   python :
      image : mcr.microsoft.com/devcontainers/python:1-3.12-bullseye
      container_name : python_Kafka_contenaire
      volumes:
      - ..:/workspace
      working_dir : /workspace
      command: tail -f /dev/null # for keep the container ruinning
